Repository sofa-framework/SofaGLFW, pull requests merged in 2024-08, with the labels that each got.

#120 Replace deprecated Data
  SofaGLFW/src/SofaGLFW/SofaGLFWWindow.cpp
Labels: pr: status to review

#118 Implement centerWindow()
  SofaGLFW/src/SofaGLFW/SofaGLFWBaseGUI.cpp
  SofaGLFW/src/SofaGLFW/SofaGLFWBaseGUI.h
  SofaGLFW/src/SofaGLFW/SofaGLFWGUI.cpp
  SofaGLFW/src/SofaGLFW/SofaGLFWGUI.h
Labels: enhancement, pr: status to review

#119 Fix triggered assert
  SofaImGui/CMakeLists.txt
  SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
  SofaImGui/src/SofaImGui/UIStrings.h
  SofaImGui/src/SofaImGui/windows/Settings.cpp
Labels: pr: status ready

#122 Save global scale in Settings
  SofaImGui/src/SofaImGui/windows/Settings.cpp
Labels: pr: status to review

#124 [GLFW, ImGui] Automatically restore camera at startup if a view file is present
  SofaGLFW/src/SofaGLFW/SofaGLFWBaseGUI.cpp
  SofaGLFW/src/SofaGLFW/SofaGLFWBaseGUI.h
  SofaGLFW/src/SofaGLFW/SofaGLFWGUI.cpp
  SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
Labels: enhancement, pr: status to review

#125 [ImGui] Add "Reset View" Option to Restore Default Windows Positions
  SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
  SofaImGui/src/SofaImGui/ImGuiGUIEngine.h
Labels: enhancement, pr: status to review

#121 [ImGui] Put config files into a folder
  SofaImGui/src/SofaImGui/AppIniFile.cpp
  SofaImGui/src/SofaImGui/AppIniFile.h
  SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
  SofaImGui/src/SofaImGui/windows/WindowState.cpp
  SofaImGui/src/SofaImGui/windows/WindowState.h
Labels: pr: status ready

#126 Logs: Add option for autoscroll
  SofaImGui/src/SofaImGui/windows/Log.cpp
  SofaImGui/src/SofaImGui/windows/Log.h
Labels: enhancement, pr: status to review

#127 Logs: Always show options
  SofaImGui/src/SofaImGui/windows/Log.cpp
Labels: enhancement, pr: status to review

#128 Fix not existing folder
  SofaImGui/src/SofaImGui/AppIniFile.cpp
  SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
Labels: pr: status ready

#130 [Imgui] Fix Display Flags
  SofaImGui/src/SofaImGui/windows/DisplayFlags.cpp
Labels: pr: status ready
